before_install:
  - npm install -g grunt-cli
before_deploy:
  - grunt before-deploy
after_deploy:
  - grunt after-deploy
language: node_js
node_js:
  - "0.10"
notifications:
  email: false
deploy:
  provider: npm
  email: "per@liedman.net"
  "on":
    all_branches: true
    tags: true
